// Code generated by scripts/generate-command-catalog.sh; DO NOT EDIT.

package commandcatalog

import (
	"github.com/tapstate/agentic-ops/packages/agentic-cli/internal/cmdkit"
	cmd000 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/agent/init"
	cmd001 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/assets/install"
	cmd002 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/check-ci-status"
	cmd003 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/contract/validate"
	cmd004 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/doctor"
	cmd005 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/feedback/bundle"
	cmd006 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/feedback/report"
	cmd007 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/fix-pr-comments"
	cmd008 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/inspect-workspace"
	cmd009 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/list-tasks"
	cmd010 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/policy/rollback"
	cmd011 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/policy/update"
	cmd012 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/policy/validate"
	cmd013 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/preflight"
	cmd014 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/prepare-pr"
	cmd015 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/profile/rollback"
	cmd016 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/profile/update"
	cmd017 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/profile/validate"
	cmd018 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/read-pr-comments"
	cmd019 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/release-agent"
	cmd020 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/resume-takeover"
	cmd021 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/takeover-task"
	cmd022 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/update/apply"
	cmd023 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/update/check"
	cmd024 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/workspace/init"
	cmd025 "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/write-evidence"
)

func RegisterAll(registry *cmdkit.Registry) {
	cmd000.Register(registry)
	cmd001.Register(registry)
	cmd002.Register(registry)
	cmd003.Register(registry)
	cmd004.Register(registry)
	cmd005.Register(registry)
	cmd006.Register(registry)
	cmd007.Register(registry)
	cmd008.Register(registry)
	cmd009.Register(registry)
	cmd010.Register(registry)
	cmd011.Register(registry)
	cmd012.Register(registry)
	cmd013.Register(registry)
	cmd014.Register(registry)
	cmd015.Register(registry)
	cmd016.Register(registry)
	cmd017.Register(registry)
	cmd018.Register(registry)
	cmd019.Register(registry)
	cmd020.Register(registry)
	cmd021.Register(registry)
	cmd022.Register(registry)
	cmd023.Register(registry)
	cmd024.Register(registry)
	cmd025.Register(registry)
}
