// Code generated by scripts/generate-command-catalog.sh; DO NOT EDIT.

package commandcatalog

import (
	"github.com/tapstate/agentic-ops/packages/agentic-cli/internal/cmdkit"
	agent_init_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/agent/init"
	assets_install_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/assets/install"
	check_ci_status_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/check-ci-status"
	contract_validate_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/contract/validate"
	doctor_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/doctor"
	feedback_bundle_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/feedback/bundle"
	feedback_report_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/feedback/report"
	fix_pr_comments_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/fix-pr-comments"
	inspect_workspace_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/inspect-workspace"
	list_tasks_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/list-tasks"
	policy_rollback_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/policy/rollback"
	policy_update_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/policy/update"
	policy_validate_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/policy/validate"
	preflight_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/preflight"
	prepare_pr_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/prepare-pr"
	profile_rollback_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/profile/rollback"
	profile_update_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/profile/update"
	profile_validate_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/profile/validate"
	read_pr_comments_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/read-pr-comments"
	release_agent_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/release-agent"
	resume_takeover_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/resume-takeover"
	switch_branch_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/switch-branch"
	takeover_task_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/takeover-task"
	task_run_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/task/run"
	update_apply_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/update/apply"
	update_check_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/update/check"
	workspace_init_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/workspace/init"
	write_evidence_cmd "github.com/tapstate/agentic-ops/packages/agentic-cli/internal/commands/write-evidence"
)

func RegisterAll(registry *cmdkit.Registry) {
	agent_init_cmd.Register(registry)
	assets_install_cmd.Register(registry)
	check_ci_status_cmd.Register(registry)
	contract_validate_cmd.Register(registry)
	doctor_cmd.Register(registry)
	feedback_bundle_cmd.Register(registry)
	feedback_report_cmd.Register(registry)
	fix_pr_comments_cmd.Register(registry)
	inspect_workspace_cmd.Register(registry)
	list_tasks_cmd.Register(registry)
	policy_rollback_cmd.Register(registry)
	policy_update_cmd.Register(registry)
	policy_validate_cmd.Register(registry)
	preflight_cmd.Register(registry)
	prepare_pr_cmd.Register(registry)
	profile_rollback_cmd.Register(registry)
	profile_update_cmd.Register(registry)
	profile_validate_cmd.Register(registry)
	read_pr_comments_cmd.Register(registry)
	release_agent_cmd.Register(registry)
	resume_takeover_cmd.Register(registry)
	switch_branch_cmd.Register(registry)
	takeover_task_cmd.Register(registry)
	task_run_cmd.Register(registry)
	update_apply_cmd.Register(registry)
	update_check_cmd.Register(registry)
	workspace_init_cmd.Register(registry)
	write_evidence_cmd.Register(registry)
}
