#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
cd "$repo_root"

module_path="$(awk '$1 == "module" {print $2; exit}' go.mod)"
commands_dir="packages/agentic-cli/internal/commands"
out="${AGENTIC_OPS_COMMAND_CATALOG_OUT:-packages/agentic-cli/internal/commandcatalog/zz_generated.go}"
tmp="$(mktemp)"

{
  cat <<'EOF'
// Code generated by scripts/generate-command-catalog.sh; DO NOT EDIT.

package commandcatalog

import (
EOF

  index=0
  while IFS= read -r file; do
    dir="${file%/command.go}"
    import_path="$module_path/$dir"
    printf '\tcmd%03d "%s"\n' "$index" "$import_path"
    index=$((index + 1))
  done < <(find "$commands_dir" -type f -name command.go -print | LC_ALL=C sort)

  cat <<'EOF'
	"github.com/tapstate/agentic-ops/packages/agentic-cli/internal/cmdkit"
)

func RegisterAll(registry *cmdkit.Registry) {
EOF

  index=0
  while IFS= read -r _file; do
    printf '\tcmd%03d.Register(registry)\n' "$index"
    index=$((index + 1))
  done < <(find "$commands_dir" -type f -name command.go -print | LC_ALL=C sort)

  cat <<'EOF'
}
EOF
} > "$tmp"

gofmt -w "$tmp"
mkdir -p "$(dirname "$out")"
mv "$tmp" "$out"
