#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
cd "$repo_root"

module_path="$(awk '$1 == "module" {print $2; exit}' go.mod)"
commands_dir="packages/agentic-cli/internal/commands"
out="${AGENTIC_OPS_COMMAND_CATALOG_OUT:-packages/agentic-cli/internal/commandcatalog/zz_generated.go}"
tmp="$(mktemp)"

command_files() {
  while IFS= read -r file; do
    if grep -q 'func Register(registry \*cmdkit.Registry)' "$file"; then
      printf '%s\n' "$file"
    fi
  done < <(find "$commands_dir" -type f -name '*_cmd.go' -print | LC_ALL=C sort)
}

alias_for_file() {
  local file="$1"
  local rel="${file#"$commands_dir"/}"
  local dir="${rel%/*}"
  printf '%s_cmd' "$dir" | tr '/-' '__'
}

{
  cat <<'EOF'
// Code generated by scripts/generate-command-catalog.sh; DO NOT EDIT.

package commandcatalog

import (
EOF

  while IFS= read -r file; do
    dir="$(dirname "$file")"
    import_path="$module_path/$dir"
    alias="$(alias_for_file "$file")"
    printf '\t%s "%s"\n' "$alias" "$import_path"
  done < <(command_files)

  cat <<'EOF'
	"github.com/tapstate/agentic-ops/packages/agentic-cli/internal/cmdkit"
)

func RegisterAll(registry *cmdkit.Registry) {
EOF

  while IFS= read -r file; do
    alias="$(alias_for_file "$file")"
    printf '\t%s.Register(registry)\n' "$alias"
  done < <(command_files)

  cat <<'EOF'
}
EOF
} > "$tmp"

gofmt -w "$tmp"
mkdir -p "$(dirname "$out")"
mv "$tmp" "$out"
